# Generated by Django 2.2.4 on 2019-08-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='sites.Site'),
        ),
    ]
